# Use an official Python runtime as the base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Django project code into the container
COPY . .

# Expose the port the Django app runs on
EXPOSE 8741

# Define the command to run the Django development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8741"]
